language: node_js

git:
  depth: 3

matrix:
  - node_js: "8"
    env: SCRIPT=lint
  - node_js: "8"
    env: SCRIPT=test:e2e

preinstall:
  - npm config set spin false
  - npm config set progress false
  - sudo apt-get -y install libfontconfig-dev

install:
  - npm install

postinstall:
  - export DISPLAY=:99
  - sudo /etc/init.d/xvfb start
  - sleep 3
  - sudo /etc/init.d/openbox start
  - npm run build:prod

test:
  - if [[ "$SCRIPT" ]]; then npm run-script $SCRIPT; fi
