environment:
  matrix:
    - nodejs_version: "6"

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run build
  - npm run test:e2e
  - npm run test:unit

build: off

cache:
  - node_modules
