export let keyboardShortcuts = [
  {keypress: 'CommandOrControl+Shift+Left', sctype: 'send', sckey: 'tabLeft', scvalue: true },
  {keypress: 'CommandOrControl+Shift+Right', sctype: 'send', sckey: 'tabRight', scvalue: true },
  {keypress: 'CommandOrControl+T', sctype: 'send', sckey: 'newTab', scvalue: true },
  {keypress: 'CommandOrControl+W', sctype: 'send', sckey: 'closeTab', scvalue: true },
  {keypress: 'CommandOrControl+K', sctype: 'send', sckey: 'clearTab', scvalue: true },
  {keypress: 'CommandOrControl+1', sctype: 'send', sckey: 'switchTab', scvalue: 0 },
  {keypress: 'CommandOrControl+2', sctype: 'send', sckey: 'switchTab', scvalue: 1 },
  {keypress: 'CommandOrControl+3', sctype: 'send', sckey: 'switchTab', scvalue: 2 },
  {keypress: 'CommandOrControl+4', sctype: 'send', sckey: 'switchTab', scvalue: 3 },
  {keypress: 'CommandOrControl+5', sctype: 'send', sckey: 'switchTab', scvalue: 4 },
  {keypress: 'CommandOrControl+6', sctype: 'send', sckey: 'switchTab', scvalue: 5 },
  {keypress: 'CommandOrControl+7', sctype: 'send', sckey: 'switchTab', scvalue: 6 },
  {keypress: 'CommandOrControl+8', sctype: 'send', sckey: 'switchTab', scvalue: 7 },
  {keypress: 'CommandOrControl+9', sctype: 'send', sckey: 'switchTab', scvalue: 8 },
  {keypress: 'CommandOrControl+0', sctype: 'send', sckey: 'switchTab', scvalue: 9 },
  {keypress: 'CommandOrControl+V', sctype: 'send', sckey: 'paste', scvalue: null },
  {keypress: 'CommandOrControl+N', sctype: 'createWindow', sckey: 'createWindow', scvalue: null },
  {keypress: 'CommandOrControl+Shift+I', sctype: 'toggleDevTools', sckey: 'toggleDevTools', scvalue: null }
]
